# Yazi keymap overrides
# Managed by GNU Stow from ~/dotfiles/yazi/keymap.toml

[[mgr.prepend_keymap]]
on   = "<A-d>"
run  = "shell -- env GDK_SCALE=1 ripdrag -x %s"
desc = "Drag selected files with ripdrag"
